name: Update AoC Badges
on:
  schedule:
    - cron: '6 5 1-25 12 *'   # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Do the readme update
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_USERID }}
          session: ${{ secrets.AOC_SESSION }}
          year: 2022
          file: 'README.md'
          #leaderboard: 'https://adventofcode.com/2020/leaderboard/private/view/00000.json'
      # Step that pushes these local changes back to your github repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md
